# Generated by Django 5.2.17 on 2026-09-08 13:16

import django.db.models.deletion
import parking_zones.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('khmer_name', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('num_of_slots', models.PositiveIntegerField(default=30)),
                ('occupied_slots', models.PositiveIntegerField(default=0)),
                ('vacant_slots', models.PositiveIntegerField(default=30)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(default='Phnom Penh', max_length=100)),
                ('price', models.PositiveIntegerField(default=3000, help_text='Price in KHR (Riel) per session/day')),
                ('description', models.TextField(blank=True)),
                ('operating_hours', models.CharField(default='06:00 - 22:00', max_length=100)),
            ],
            options={
                'verbose_name': 'Parking Zone',
                'verbose_name_plural': 'Parking Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(default=parking_zones.models.generate_ticket_code, max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('plate_number', models.CharField(help_text='Cambodian vehicle plate e.g. 2AZ-1234', max_length=40)),
                ('phone_number', models.CharField(help_text='Contact phone e.g. +855 12 345 678', max_length=30)),
                ('checked_out', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('parking_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='parking_zones.parkingzone')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_on', '-id'],
            },
        ),
    ]
