# Generated by Django 5.2.17 on 2026-09-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_zones', '0002_seed_phnom_penh_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='access_token',
            field=models.CharField(blank=True, help_text='Opaque token for scannable access QR', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='arrival_deadline',
            field=models.DateTimeField(blank=True, help_text='Arrival deadline for unpaid same-day holds (3 hours)', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='balance_paid',
            field=models.PositiveIntegerField(default=0, help_text='Exit balance paid in KHR'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, help_text='Actual gate entry timestamp', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, help_text='Actual gate exit timestamp', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='daily_rate',
            field=models.PositiveIntegerField(default=3000, help_text='Snapshotted rate in KHR per day'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0, help_text='Deposit paid in KHR'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='exit_authorized_until',
            field=models.DateTimeField(blank=True, help_text='5-minute gate departure authorization window', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='finish_time',
            field=models.DateTimeField(blank=True, help_text='Booked exit deadline', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Flagged for staff reconciliation from pre-workflow system'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='overstay_multiplier',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Overstay multiplier, default 2x', max_digits=3),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='Checkout timeout for deposit payment', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('DEPOSIT', 'Pay first day now (កក់ប្រាក់ថ្ងៃដំបូង)'), ('PAY_AT_EXIT', 'Pay at exit (ទូទាត់ពេលចេញ)')], default='DEPOSIT', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid (មិនទាន់ទូទាត់)'), ('PARTIALLY_PAID', 'Partially Paid / Deposit (បានកក់ប្រាក់)'), ('PAID', 'Fully Paid (បានទូទាត់រួច)')], default='UNPAID', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Booked arrival window start', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PAYMENT_PENDING', 'Payment Pending (រង់ចាំការបង់ប្រាក់)'), ('CONFIRMED', 'Confirmed Hold (បានបញ្ជាក់ការកក់)'), ('CHECKED_IN', 'Checked In (បានចូលចំណត)'), ('CHECKED_OUT', 'Checked Out (បានចេញពីចំណត)'), ('EXPIRED', 'Expired (ផុតកំណត់)'), ('CANCELLED', 'Cancelled (បានបោះបង់)')], default='CONFIRMED', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_amount',
            field=models.PositiveIntegerField(default=0, help_text='Final total billed in KHR'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('DEPOSIT', 'First Day Deposit'), ('EXIT_BALANCE', 'Exit Balance Payment'), ('REFUND', 'Refund')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in KHR')),
                ('currency', models.CharField(default='KHR', max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('provider', models.CharField(default='DEMO', max_length=30)),
                ('provider_ref', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parking_zones.reservation')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
