# Generated by Django 5.2.17 on 2026-09-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_zones', '0004_reconcile_legacy_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_days',
            field=models.PositiveIntegerField(default=1, help_text='Reserved duration in 24-hour parking days'),
        ),
    ]
