# Generated by Django 5.2.17 on 2026-09-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_zones', '0005_reservation_reserved_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Cancellation timestamp for cooldown tracking', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_forfeited',
            field=models.BooleanField(default=False, help_text='True if first-day payment was retained due to customer no-show'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrival_deadline',
            field=models.DateTimeField(blank=True, help_text='Arrival deadline (3 hours for pay-at-exit; 5 hours after verified deposit)', null=True),
        ),
    ]
