# Generated by Django 5.2.17 on 2026-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_zones', '0006_reservation_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='latitude',
            field=models.FloatField(blank=True, default=11.5564, help_text='Latitude for map coordinates', null=True),
        ),
        migrations.AddField(
            model_name='parkingzone',
            name='longitude',
            field=models.FloatField(blank=True, default=104.9282, help_text='Longitude for map coordinates', null=True),
        ),
    ]
