# Generated by Django 5.2.17 on 2026-09-10 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_zones', '0007_parkingzone_latitude_parkingzone_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingzone',
            name='walk_in_price',
            field=models.PositiveIntegerField(default=7000, help_text='Walk-in rate in KHR per day'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_walk_in',
            field=models.BooleanField(default=False, help_text='True for walk-in tickets issued at gate'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone e.g. +855 12 345 678', max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Cambodian vehicle plate e.g. 2AZ-1234', max_length=40),
        ),
    ]
