# Generated by Django 5.2.17 on 2026-09-10 14:08

import parking_zones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_zones', '0008_parkingzone_walk_in_price_reservation_is_walk_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='plate_lookup_hmac',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Keyed HMAC-SHA256 lookup index for exact matching', max_length=64),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plate_number',
            field=parking_zones.models.EncryptedPlateCharField(blank=True, help_text='Cambodian vehicle plate e.g. 2AZ-1234', max_length=255),
        ),
    ]
